ACCEPT NOMBRE PROMPT'INTRODUCE TU NOMBRE'
ACCEPT EDAD PROMPT'INTRODUCE TU EDAD'
DECLARE 
    ED NUMBER(3) := &EDAD;
    NOM VARCHAR2(20) := '&NOMBRE';
BEGIN
    IF ED > 18 THEN
    DBMS_OUTPUT.PUT_LINE( NOM ||' ES MAYOR DE EDAD');
    ELSE
        DBMS_OUTPUT.PUT_LINE(NOM ||' ES MENOR DE EDAD');
    END IF;
END;
/