ACCEPT NUMBER4 PROMPT 'INTODUCE UN NUMERO'
DECLARE 
    NUM NUMBER(10):=&NUMBER4;
    NUM2 NUMBER(10):=1;
BEGIN
    WHILE NUM2 <= NUM LOOP
    DBMS_OUTPUT.PUT_LINE(NUM2);
    NUM2 := NUM2 + 1;
    END LOOP;
END;
/