CREATE OR REPLACE FUNCTION CONTARVOCALES (CADENA VARCHAR2) RETURN NUMBER IS
    
    CONT NUMBER(3) := 0;
BEGIN

    FOR I IN 1..LENGTH(CADENA) LOOP
        IF UPPER(SUBSTR(CADENA,I,1)) IN ('A','E','I','O','U') THEN
            CONT := CONT + 1; 
        END IF;
    END LOOP;
END;
/