CREATE OR REPLACE FUNCTION CONTARCHAR(CADENA VARCHAR2,CAR VARCHAR2) RETURN NUMBER IS
    CONT NUMBER(3) := 0;

BEGIN
    FOR I IN 1..LENGTH(CADENA) LOOP
        IF UPPER(SUBSTR(CADENA,I,1)) = CAR THEN 
            CONT:= CONT + 1;
        END IF;
    END LOOP;

    RETURN CONT;
END;
/