
ACCEPT MODULO PROMPT 'INTROUCE EL NUMERO DEL MODULO'
ACCEPT NOTA PROMPT 'INTROUCE LA NOTA DEL MODULO (0-10) CON DOS DECIMALES'
DECLARE
 GRADE NUMBER(4,2):= &NOTA;
 MODU VARCHAR2(50):= '&MODULO';
 BEGIN 
    IF GRADE < 4.50 OR GRADE < 0 THEN
        DBMS_OUTPUT.PUT_LINE('lA NOTA ' || GRADE || ' ES UN SUSPENSO');
    ELSE
        IF GRADE < 5.99 THEN
         DBMS_OUTPUT.PUT_LINE('lA NOTA ' || GRADE || ' ES UN APROBADO');
        ELSE
            IF GRADE < 7.99 THEN
             DBMS_OUTPUT.PUT_LINE('lA NOTA ' || GRADE || ' ES UN NOTATBLE');
            ELSE
              DBMS_OUTPUT.PUT_LINE('lA NOTA ' || GRADE || ' ES UN SORESALIENTE');
            END IF;
        END IF;
    END IF;
END;
/
