CREATE TABLE ASOCIACION(
    CIF CHAR(10) PRIMARY KEY,
    TIPO VARCHAR2(10) NOT NULL,
    DENOMINACION   CHAR(2) NOT NULL,
    UTILIDAD VARCHAR2(50),
    DIRECCION VARCHAR2(50),
    PROVINCIA VARCHAR2(10),
    CONSTRAINT DENOMINACION_CK CHECK (DENOMINACION IN('SI','NO'))
)