CREATE TABLE PERSONA(
    DNI     CHAR(10) PRIMARY KEY,
    NOM     CHAR(15),
    AP1     CHAR(15),
    AP2     CHAR(15),
    TIPO_PERSONA  CHAR(1) NOT NULL,     
    CONSTRAINT TIPO_PERSONA_CK CHECK (TIPO_PERSONA IN ('TRABAJADOR','SOCIO'))    
)